service: dashboard-server

frameworkVersion: "3"

plugins:
  - serverless-dotenv-plugin

package:
  patterns:
    - "!./**"
    - "package.json"
    - "node_modules/**"
    - "dist/**"

provider:
  name: aws
  region: eu-west-3
  runtime: nodejs18.x
  httpApi:
    cors: true

functions:
  dashboard-server:
    handler: dist/lambda.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true