name: Deploy lambda

on:
  push:
    branches:
      - main

jobs:
  deploy_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: '18.18.2'

      - name: Install dependencies
        run: npm install

      - name: Compile typescript
        run: npm run build

      - name: Deploy project serverless
        run: npm run deploy
      
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-3'
          SOURCE_DIR: 'dist'


